site_name: 'UDB Metrics Reporting for cpp_check'
site_description: 'Metrics and Dependency report for a UDB.'
site_author: 'Roy Crippen'

use_directory_urls: false

theme:
  name: null
  custom_dir: ../../mkdocs_ivory
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []


markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: true
  version: v0.0.1

plugins:
    - search:
        lang: ['en']
        prebuild_index: true

