site_name: 'UDB Metrics Reporting for cpp_check'
site_description: 'Metrics and Dependency report for a UDB.'
site_author: 'Roy Crippen'

use_directory_urls: false

theme:
  name: null
  custom_dir: ../../mkdocs_ivory
  # Copy settings from mkdocs_theme.yml, which is ignored by custom_dir themes.
  static_templates:
    - 404.html

  include_search_page: true
  search_index_only: false

  highlightjs: true
  hljs_languages: []


markdown_extensions:
  - toc:
      permalink: '#'

extra:
  history_buttons: true
  version: v0.0.1

plugins:
    - search:
        lang: ['en']
        prebuild_index: true

nav:
- Usage: index.md
- Metrics:
    - Application Metrics: Metrics/application-metrics.md
    - include:
        - include Metrics: Metrics/include/include-metrics.md
        - gtest:
            - gtest Metrics: Metrics/include/gtest/gtest-metrics.md
            - File Metrics and Dependencies: Metrics/include/gtest/zzz-file-metrics.md
            - internal:
                - internal Metrics: Metrics/include/gtest/internal/internal-metrics.md
                - File Metrics and Dependencies: Metrics/include/gtest/internal/zzz-file-metrics.md
                - custom:
                    - custom Metrics: Metrics/include/gtest/internal/custom/custom-metrics.md
                    - File Metrics and Dependencies: Metrics/include/gtest/internal/custom/zzz-file-metrics.md
    - src:
        - src Metrics: Metrics/src/src-metrics.md
        - File Metrics and Dependencies: Metrics/src/zzz-file-metrics.md
    - test:
        - test Metrics: Metrics/test/test-metrics.md
        - File Metrics and Dependencies: Metrics/test/zzz-file-metrics.md
- Reports:
    - Direct Circular File References: Reports/circular_file_refs.md
    - File List Indented: Reports/file_list_indented_sloc.md
    - Red Metrics: Reports/red_metrics.md
